name: Format

on:
  push:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Format check and auto-fix
        id: format
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if ! bun run format:check; then
              echo "has_issues=true" >> $GITHUB_OUTPUT
              exit 1
            fi
          else
            bun run format
            
            if [[ -n "$(git status --porcelain)" ]]; then
              git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              git add -A
              git commit -m "style: format code with prettier"
              git push
            fi
          fi

      - name: Comment PR
        if: failure() && steps.format.outputs.has_issues == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Please run `bun run format` locally and commit the changes.'
            })
